# Generated by Django 3.2.9 on 2021-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(null=True, upload_to='Imagenes/', verbose_name='Imagen del producto')),
            ],
        ),
    ]
